name: Deployment
on:
  push:
    branches:
      - 'master'
jobs:
  Deploy-To-Windows-Server:
    runs-on: self-hosted
    steps:
      # - uses: actions/checkout@v3
      #   with:
      #     ref: develop
      - run: git pull origin
      - run: lerna bootstrap
      - run: yarn cd
